// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
<<<<<<< HEAD
      return web;
=======
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
>>>>>>> ff87001613ae57d511bb44ec13f834590f551c8a
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

<<<<<<< HEAD
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhKR33EJZObb31q5wiyjK32iskOOyBNWg',
    appId: '1:130116297200:web:68f2cedb3dcaf3e8fd7d35',
    messagingSenderId: '130116297200',
    projectId: 'algoriju-moapp',
    authDomain: 'algoriju-moapp.firebaseapp.com',
    storageBucket: 'algoriju-moapp.appspot.com',
  );

=======
>>>>>>> ff87001613ae57d511bb44ec13f834590f551c8a
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATwamVk_ty8rsWZjfMgHZGTxhLp-tyPzM',
    appId: '1:130116297200:android:80a7ba99a63ff2abfd7d35',
    messagingSenderId: '130116297200',
    projectId: 'algoriju-moapp',
    storageBucket: 'algoriju-moapp.appspot.com',
  );
}
